if filereadable(expand('$HOME/.vim/vimrc.visual'))
	source $HOME/.vim/vimrc.visual	" Loading vimrc.visual
endif

if filereadable(expand('$HOME/.vim/vimrc.neobundle'))
	source $HOME/.vim/vimrc.neobundle	" Load vimrc.neobundle
endif

if filereadable(expand('$HOME/.vim/vimrc.keybind'))
	source $HOME/.vim/vimrc.keybind		" Load vimrc.keybind
endif

if filereadable(expand('$HOME/.vim/vimrc.tweetvim'))
	source $HOME/.vim/vimrc.tweetvim 	" Load vimrc.tweetvim
endif

if filereadable(expand('$HOME/.vim/vimrc.local'))
	source $HOME/.vim/vimrc.local		" Load vimrc.local
endif

set nocp
set ls=2
set ruler
set number
set ignorecase
set modeline
set nobackup
set noswapfile
set nowrap
set hidden
set backspace=indent,eol,start
set cursorline
set cindent
set incsearch

set tabstop=4
set shiftwidth=4
set softtabstop=0

syntax on
filetype plugin on
set ofu=syntaxcomplete#Complete
set ambiwidth=double

colorscheme desert
set background=dark
highlight Pmenu ctermbg=blue ctermfg=white
highlight PmenuSel ctermbg=blue ctermfg=red
highlight PmenuSbar ctermbg=cyan ctermfg=green
highlight PmenuThumb ctermbg=white ctermfg=red

set completeopt=longest,menuone

let Tlist_Use_Right_Window = 1
let Tlist_WinWidth = 50
